name: Simple GCP Auth Test

on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Check authentication
        run: |
          echo "Checking authentication status:"
          gcloud auth list
          
          echo "Active account:"
          gcloud config list account
          
          echo "Testing storage access:"
          gsutil ls
          
          echo "Testing compute access:"
          gcloud compute zones list --limit=3
          
          echo "Testing project access:"
          gcloud projects describe $GCP_PROJECT_ID