name: Configure Infrastructure with Ansible

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (qa/prod)'
        required: true
        default: 'qa'
      config_type:
        description: 'Configuration type (all, frontend, backend, database)'
        required: true
        default: 'all'

jobs:
  setup-ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ansible
      run: |
        pip install ansible

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Create temporary key file and configure gcloud
      run: |
        mkdir -p $HOME/.config/gcloud
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > $HOME/gcp-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/region us-central1

    - name: Run Ansible Playbooks
      run: |
        cd ansible
        ansible-playbook playbooks/${{ github.event.inputs.config_type }}.yml -e "environment=${{ github.event.inputs.environment }}"