name: Configure Terraform Backend

on:
  workflow_dispatch:  # Allows manual triggering

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}

jobs:
  configure-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create GCS Bucket for Terraform State
        run: |
          # Ensure proper bucket name format (strip any gs:// prefix if present)
          BUCKET_NAME="${{ secrets.TERRAFORM_STATE_BUCKET }}"
          BUCKET_NAME=${BUCKET_NAME#gs://}
          gsutil mb -p ${{ secrets.GCP_PROJECT_ID }} -c STANDARD -l ${{ secrets.GCP_REGION }} gs://$BUCKET_NAME

      - name: Update backend configuration
        run: |
          # Ensure proper bucket name format (strip any gs:// prefix if present)
          BUCKET_NAME="${{ secrets.TERRAFORM_STATE_BUCKET }}"
          BUCKET_NAME=${BUCKET_NAME#gs://}
          sed -i "s/# terraform {/terraform {/g; s/#   backend \"gcs\" {/  backend \"gcs\" {/g; s/#     bucket = \"epam-bucket-gcp2025\"/    bucket = \"$BUCKET_NAME\"/g; s/#     prefix = \"terraform\\/state\"/    prefix = \"terraform\\/state\"/g; s/# }//g" terraform/backend.tf
          
      - name: Commit and Push Backend Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add terraform/backend.tf
          git commit -m "Configure backend for GCS" || exit 0  # Exit 0 to prevent failure if no changes
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}