name: 1.7 Foundation – Configure Terraform Backend

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: "GCS Bucket Name (leave empty to use TERRAFORM_STATE_BUCKET secret)"
        required: false
      environment:
        description: "Environment (dev / staging / prod)"
        required: false
        default: "dev"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  configure-terraform-backend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'prod' && 'production' || 'development' }}

    steps:
    # 0) Checkout repository
    - uses: actions/checkout@v3

    # 1) Authenticate to Google Cloud
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 2) Install gcloud / gsutil
    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        install_components: "gsutil"

    # 3) Install Terraform  ← NEW
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7         # pin the version you need

    # 4) Quick auth sanity-check
    - name: Verify authentication
      run: |
        gcloud auth list --filter=status:ACTIVE
        gcloud projects describe "$GCP_PROJECT_ID" --format='get(projectId)'

    # 5) Determine bucket name
    - name: Determine bucket name
      run: |
        if [ -n "${{ inputs.bucket_name }}" ]; then
          BN="${{ inputs.bucket_name }}"
        elif [ -n "${{ secrets.TERRAFORM_STATE_BUCKET }}" ]; then
          BN="${{ secrets.TERRAFORM_STATE_BUCKET }}"
        else
          echo "❌ No bucket name provided and TERRAFORM_STATE_BUCKET secret is empty"
          exit 1
        fi
        BN="${BN#gs://}"
        BN="${BN%/}"
        echo "BUCKET_NAME=$BN" >> "$GITHUB_ENV"
        echo "Using bucket: $BN"

    # 6) Check if bucket exists
    - id: check
      name: Check if bucket exists
      run: |
        if gsutil ls "gs://${{ env.BUCKET_NAME }}" >/dev/null 2>&1; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi

    # 7) Fail if bucket doesn’t exist
    - name: Verify bucket exists
      if: steps.check.outputs.exists == 'false'
      run: |
        echo "❌ Bucket gs://${{ env.BUCKET_NAME }} does not exist"
        echo "Create it first with the 'Create GCS Bucket' workflow"
        exit 1

    # 8) Update backend.tf
    - name: Update Terraform backend
      run: |
        echo "Updating Terraform backend..."
        cp terraform/backend.tf terraform/backend.tf.backup
        sed -i "s/bucket = \"[^\"]*\"/bucket = \"${{ env.BUCKET_NAME }}\"/g" terraform/backend.tf
        # Uncomment if backend block is commented out
        sed -i 's/^# *$backend "gcs"$/\1/' terraform/backend.tf

        echo "backend.tf after update:"
        cat terraform/backend.tf

    # 9) Terraform init           ← Terraform now installed
    - name: Initialize Terraform
      run: |
        echo "Initializing Terraform with GCS backend..."
        cd terraform
        if terraform init -reconfigure; then
          echo "✓ Terraform initialized"
        else
          echo "✗ Terraform initialization failed"
          cp backend.tf.backup backend.tf   # path fixed
          exit 1
        fi

    # 10) Terraform validate
    - name: Validate configuration
      run: |
        cd terraform
        terraform validate

    # 11) Commit and push backend.tf
    - name: Commit backend changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name  "GitHub Action"
        git add terraform/backend.tf
        if ! git diff --cached --quiet; then
          git commit -m "Configure Terraform backend -> gs://${{ env.BUCKET_NAME }}"
          git push
        fi

    # 12) Final confirmation
    - name: Confirm setup
      run: |
        echo "=== Terraform Backend Configured ==="
        echo "Bucket : gs://${{ env.BUCKET_NAME }}"
        echo "Project: $GCP_PROJECT_ID"