name: 2.1-infrastructure-vpc-creation.yml

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (qa/prod)'
        required: true
        default: 'qa'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_ZONE: ${{ secrets.GCP_ZONE }}

jobs:
  vpc-creation:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'prod' && 'production' || 'development' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan for VPC
        run: |
          terraform plan \
            -target=google_compute_network.custom_vpc \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="region=${{ secrets.GCP_REGION }}" \
            -var="db_root_password=${{ secrets.DB_ROOT_PASSWORD }}" \
            -var="ssh_allowed_ips=${{ secrets.SSH_ALLOWED_IPS }}" \
            -var="frontend_machine_type=e2-micro" \
            -var="backend_machine_type=e2-micro"
        working-directory: ./terraform

      - name: Terraform Apply VPC
        run: terraform apply -auto-approve
        working-directory: ./terraform
        
      - name: Output VPC Information
        run: |
          echo "VPC has been created successfully"
          terraform output -raw vpc_id