name: '2.8.5 - Database Initialization'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - prod

env:
  TF_WORKSPACE: ${{ inputs.environment || 'qa' }}

jobs:
  deploy-database-init:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Setup Ansible
      run: |
        pip install ansible

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        token_format: access_token

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Init
      run: |
        cd terraform
        terraform init \
          -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
          -backend-config="prefix=terraform/state/${{ env.TF_WORKSPACE }}/terraform"

    - name: Terraform Select/Create Workspace
      run: |
        cd terraform
        # The TF_WORKSPACE environment variable already sets the workspace
        # Use terraform workspace show to confirm the workspace is correctly selected
        terraform workspace list
        # No need to manually select since TF_WORKSPACE is already set

    - name: Get Terraform Outputs
      id: tf-outputs
      run: |
        cd terraform
        # Refresh the state to ensure we have the latest outputs
        terraform refresh
        # Capture each output separately to handle potential errors
        DB_HOST=$(terraform output -raw database_connection_name 2>/dev/null || echo "")
        DB_NAME=$(terraform output -raw database_name 2>/dev/null || echo "")
        DB_USER=$(terraform output -raw database_user 2>/dev/null || echo "")
        DB_PASSWORD=$(terraform output -raw database_password 2>/dev/null || echo "")
        BACKEND_IP=$(terraform output -raw backend_internal_ip 2>/dev/null || echo "")
        
        # Only write to GITHUB_OUTPUT if the values exist
        if [ -n "$DB_HOST" ]; then
          echo "db_host=$DB_HOST" >> $GITHUB_OUTPUT
        else
          echo "Error: database_connection_name not found in Terraform outputs"
          exit 1
        fi
        
        if [ -n "$DB_NAME" ]; then
          echo "db_name=$DB_NAME" >> $GITHUB_OUTPUT
        else
          echo "Error: database_name not found in Terraform outputs"
          exit 1
        fi
        
        if [ -n "$DB_USER" ]; then
          echo "db_user=$DB_USER" >> $GITHUB_OUTPUT
        else
          echo "Error: database_user not found in Terraform outputs"
          exit 1
        fi
        
        if [ -n "$DB_PASSWORD" ]; then
          echo "db_password=$DB_PASSWORD" >> $GITHUB_OUTPUT
        else
          echo "Error: database_password not found in Terraform outputs"
          exit 1
        fi
        
        if [ -n "$BACKEND_IP" ]; then
          echo "backend_ip=$BACKEND_IP" >> $GITHUB_OUTPUT
        else
          echo "Error: backend_internal_ip not found in Terraform outputs"
          exit 1
        fi

    - name: Get OS Login SSH Username for Backend
      id: backend-user
      run: |
        BACKEND_SSH_USER=$(gcloud compute os-login describe-profile --format="value(response.posixAccounts.username)" --impersonate-service-account="app-sa-${{ env.TF_WORKSPACE }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com")
        echo "BACKEND_USER=$BACKEND_SSH_USER" >> $GITHUB_OUTPUT

    - name: Create Ansible Inventory
      run: |
        cat > ansible/inventory/${{ env.TF_WORKSPACE }}_temp.ini << EOF
        [backend]
        ${{ steps.tf-outputs.outputs.backend_ip }} ansible_user=${{ steps.backend-user.outputs.BACKEND_USER }} ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

        [backend:vars]
        ansible_python_interpreter=/usr/bin/python3
        db_connection_name=${{ steps.tf-outputs.outputs.db_host }}
        db_host=127.0.0.1
        db_name=${{ steps.tf-outputs.outputs.db_name }}
        db_user=${{ steps.tf-outputs.outputs.db_user }}
        db_password=${{ steps.tf-outputs.outputs.db_password }}
        EOF

    - name: Run Database Schema Initialization with Ansible
      run: |
        ansible-playbook -i ansible/inventory/${{ env.TF_WORKSPACE }}_temp.ini ansible/playbooks/database_init.yml \
          --extra-vars "db_host=127.0.0.1" \
          --extra-vars "db_name=${{ steps.tf-outputs.outputs.db_name }}" \
          --extra-vars "db_user=${{ steps.tf-outputs.outputs.db_user }}" \
          --extra-vars "db_password=${{ steps.tf-outputs.outputs.db_password }}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: False