name: Destroy Infrastructure with Workspace Management

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (qa/prod)'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - prod
      auto_approve:
        description: 'Auto approve destruction (use with extreme caution - this will delete infrastructure!)'
        required: true
        default: false
        type: boolean

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_ZONE: ${{ secrets.GCP_ZONE }}

jobs:
  authenticate:
    runs-on: ubuntu-latest
    outputs:
      authenticated: ${{ steps.auth-test.outputs.authenticated }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Test GCP Authentication
        id: auth-test
        run: |
          gcloud auth list
          if gcloud projects describe ${{ secrets.GCP_PROJECT_ID }} > /dev/null 2>&1; then
            echo "authenticated=true" >> $GITHUB_OUTPUT
            echo "Authentication successful"
          else
            echo "Authentication failed"
            exit 1
          fi

  destroy-infrastructure:
    needs: authenticate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'prod' && 'production' || 'qa' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Terraform Backend and Workspace
        run: |
          cd ./terraform
          
          # Initialize Terraform with existing backend configuration
          terraform init
          
          # List existing workspaces
          echo "Current workspaces:"
          terraform workspace list
          
          # Create or select the appropriate workspace
          if terraform workspace list | grep -q "^* ${{ inputs.environment }}$"; then
            echo "Switching to existing workspace: ${{ inputs.environment }}"
            terraform workspace select ${{ inputs.environment }}
          else
            echo "Creating new workspace: ${{ inputs.environment }}"
            terraform workspace new ${{ inputs.environment }}
          fi
          
          # Verify we have an existing state before attempting to destroy
          if [ -f "terraform.tfstate" ] || [ -f "terraform.tfstate.backup" ]; then
            # List resources to be destroyed
            echo "Resources that will be destroyed:"
            terraform plan -destroy -out=tfplan.binary
          else
            echo "No state file found for ${{ inputs.environment }}. Nothing to destroy."
            exit 1
          fi
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.GCP_REGION }}
          TF_VAR_zone: ${{ secrets.GCP_ZONE }}
          TF_VAR_db_root_password: ${{ secrets.DB_ROOT_PASSWORD }}

      - name: Show Destroy Plan
        run: |
          cd ./terraform
          terraform show -no-color -destroy tfplan.binary

      - name: Terraform Destroy
        if: ${{ inputs.auto_approve == true }}
        run: |
          cd ./terraform
          echo "Starting infrastructure destruction for ${{ inputs.environment }} environment..."
          terraform destroy -auto-approve tfplan.binary || {
            echo "Terraform destroy failed - cleaning up lock file"
            gsutil ls gs://epam-bucket-gcp2025/terraform/state/${{ inputs.environment }}.tflock && \
            gsutil rm gs://epam-bucket-gcp2025/terraform/state/${{ inputs.environment }}.tflock || true
            exit 1
          }
          
          echo "Infrastructure destruction completed for ${{ inputs.environment }} environment"
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ secrets.GCP_REGION }}
          TF_VAR_zone: ${{ secrets.GCP_ZONE }}
          TF_VAR_db_root_password: ${{ secrets.DB_ROOT_PASSWORD }}
          
      - name: Warning for Manual Destroy Required
        if: ${{ inputs.auto_approve == false }}
        run: |
          echo "Manual approval required. Destroy plan has been generated but not executed."
          echo "To destroy manually, run: terraform destroy tfplan.binary in the terraform directory"
          echo "WARNING: This will permanently delete infrastructure. Please review the plan details carefully."

      - name: Cleanup Plan File
        if: ${{ always() }}
        run: |
          cd ./terraform
          rm -f tfplan.binary