name: Basic Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Hello World
      run: |
        echo "Hello World from GitHub Actions!"
        echo "This is a basic test workflow"
        
    - name: Another Hello
      run: |
        echo "Another Hello from the workflow!"
        echo "Workflow is working correctly"
        
    - name: Final Message
      run: |
        echo "✅ Workflow completed successfully!"
        echo "All steps executed with basic echo commands"