name: Create GCS Bucket for Terraform State

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      bucket_name:
        description: 'Bucket name'
        required: true
        default: 'epam-bucket-gcp2025'
      location:
        description: 'Location for the bucket'
        required: true
        default: 'us-central1'

jobs:
  create-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Echo Workflow Start
      run: |
        echo "Starting GCS bucket creation workflow..."
        echo "Bucket name: ${{ github.event.inputs.bucket_name }}"
        echo "Location: ${{ github.event.inputs.location }}"

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Create GCS Bucket
      run: |
        echo "Creating GCS bucket: ${{ github.event.inputs.bucket_name }}"
        gsutil mb -p ${{ secrets.GCP_PROJECT_ID }} -c STANDARD -l ${{ github.event.inputs.location }} gs://${{ github.event.inputs.bucket_name }}/
        
    - name: Enable versioning on bucket
      run: |
        echo "Enabling versioning on bucket: ${{ github.event.inputs.bucket_name }}"
        gsutil versioning set on gs://${{ github.event.inputs.bucket_name }}/
        
    - name: Verify bucket creation
      run: |
        echo "Verifying bucket: ${{ github.event.inputs.bucket_name }}"
        gsutil ls -b gs://${{ github.event.inputs.bucket_name }}/
        
    - name: Set IAM permissions for service account
      run: |
        echo "Setting IAM permissions for service account..."
        # The authenticated service account should already have necessary permissions
        # This step is just to ensure the service account has bucket access
        PROJECT_NUMBER=$(gcloud projects describe ${{ secrets.GCP_PROJECT_ID }} --format="value(projectNumber)")
        gsutil iam ch serviceAccount:$PROJECT_NUMBER-compute@developer.gserviceaccount.com:objectCreator gs://${{ github.event.inputs.bucket_name }}/
        gsutil iam ch serviceAccount:$PROJECT_NUMBER-compute@developer.gserviceaccount.com:objectViewer gs://${{ github.event.inputs.bucket_name }}/
        gsutil iam ch serviceAccount:$PROJECT_NUMBER-compute@developer.gserviceaccount.com:legacyBucketWriter gs://${{ github.event.inputs.bucket_name }}/
        
    - name: Final Status
      run: |
        echo "✅ GCS Bucket ${{ github.event.inputs.bucket_name }} created successfully!"
        echo "Project: ${{ secrets.GCP_PROJECT_ID }}"
        echo "Location: ${{ github.event.inputs.location }}"
        echo ""
        echo "You can now use this bucket for Terraform state management."