name: Database Health Check

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    # Run every hour - adjust as needed
    - cron: '0 * * * *'

env:
  TF_WORKSPACE: qa

jobs:
  database-health-check:
    runs-on: ubuntu-latest
    environment: qa
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        token_format: access_token

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Run Database Health Check
      run: |
        chmod +x scripts/database_check.sh
        ./scripts/database_check.sh
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}