name: Terraform GCP Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5
        terraform_wrapper: false

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Terraform for GCP
      run: |
        echo "Setting up Terraform for GCP..."
        cd terraform
        terraform init
        echo "✅ Terraform initialized for GCP"

    - name: Validate Terraform Configuration
      run: |
        echo "Validating Terraform configuration..."
        cd terraform
        terraform validate
        echo "✅ Terraform configuration is valid"

    - name: Format Check
      run: |
        echo "Checking Terraform formatting..."
        cd terraform
        terraform fmt -check
        echo "✅ Terraform formatting check completed"

    - name: Terraform Plan (Read-Only)
      run: |
        echo "Running Terraform plan (read-only)..."
        cd terraform
        terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -detailed-exitcode || true
        echo "✅ Terraform plan completed (no changes made)"

    - name: Final Verification
      run: |
        echo "✅ Terraform GCP test completed successfully!"
        echo "Terraform can connect to GCP project: ${{ secrets.GCP_PROJECT_ID }}"
        echo "All tests passed: init, validate, fmt, plan"